branches:
  only:
    - master
image: Visual Studio 2017
version: '2.0.{build}'
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
nuget:
  account_feed: true
before_build:
- cmd: nuget restore src\LogDNA.sln
# turning default build off since it doesn't handle DLL and NuGet versioning properly with .NET Core
build: off
# adapted msbuild command which addresses versioning in .NET Core
build_script:
- msbuild src\LogDNA.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release;PackageVersion=%APPVEYOR_BUILD_VERSION%;Version=%APPVEYOR_BUILD_VERSION%
# turning default test off since it doesn't handle .NET Core
test: off
# xUnit execution
test_script:
- dotnet test "src\UnitTests\UnitTests.csproj" -c Release --no-build
artifacts:
- path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: uMFJIRdMd8WBrUSsuBDxCm/Uo8/PK22UwPZtCJm5s6qr+3BWzin/XHDx3+hZU+Xz
  skip_symbols: false
  artifact: /.*\.nupkg/
notifications:
- provider: Slack
  incoming_webhook:
    secure: Mtm90XxM7T+5NlCQZ6xlQMqJ4I88JWmn6Vf3CgsTmhmcWPZHzIX5v5UxiOxtXqlpqWYVaXLCBsxU3vCMw+Ru9rhtrVag0a9ZvTzg59uU4KM=